function on_message(self, message_id, message, sender) --Called by enemy
	if message_id == hash("spawnPowerup") then
		local pos = message.position --Spawns powerup on enemy's current position
		local powerupId = factory.create("#powerupFactory", pos) --Spawns new powerup object
		local powerupType = math.random(1,3) --Randomly determines the type of powerup that will be spawned
		msg.post(powerupId, "powerup", {powerupType = powerupType}) --Posts the powerup type to this new powerup object
	end
end